version: "3.9"
services:
  app:
    image: assigned-courses-app
    container_name: Assigned_courses_app
    build:
      context: .
    ports:
      - 8093:8093
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trainingManagementPlatform
    networks:
      - backend_network

networks:
  backend_network:
    external: true

#
# Commands:
#
# docker-compose up                -> used to create a docker container
# docker-compose down              -> used to destroy a docker container
#